#!/bin/bash

export IMAGE=$1
export ENV1=$2
export ENV2=$3

echo CLEANING
docker rmi -f $IMAGE:$ENV1
docker rmi -f $IMAGE:$ENV2
echo CLEAN

echo PULLING

docker pull $IMAGE:$ENV1
docker pull $IMAGE:$ENV2

echo CHECKING
export DIGEST1=$(docker images --no-trunc | grep $IMAGE | grep $ENV1 | awk '{print $3}')
export DIGEST2=$(docker images --no-trunc | grep $IMAGE | grep $ENV2 | awk '{print $3}')
if [ "$DIGEST1" != "$DIGEST2" ]; then
    echo DIFF DETECTED PUSHING
    docker rmi $IMAGE:$ENV2
    docker tag $IMAGE:$ENV1 $IMAGE:$ENV2
    docker push $IMAGE:$ENV2
    echo PUSHED
fi
echo CLEANING
docker rmi $IMAGE:$ENV1
docker rmi $IMAGE:$ENV2
echo CLEAN
