#!/bin/bash

export IMAGE=$1
export ENV1=$2
export ENV2=$3

docker pull $IMAGE:$ENV1
docker pull $IMAGE:$ENV2

# if the number of lines output by the diff grabber is greater than 2, there is a difference, thus push promotee to their new office
if (( $(./docker-diff $IMAGE:$ENV1 $IMAGE:$ENV2 | wc -l) > 2 )); then
    echo hello
    docker tag $IMAGE:$ENV1 $IMAGE:$ENV2
    docker push $IMAGE:$ENV2

fi
docker rmi $IMAGE:$ENV1
docker rmi $IMAGE:$ENV2
