#!/bin/bash

export IMAGE=$1
export ENV1=$2
export ENV2=$3

echo PULLING

docker pull $IMAGE:$ENV1
docker pull $IMAGE:$ENV2

echo CHECKING
# if the number of lines output by the diff grabber is greater than 2, there is a difference, thus push promotee to their new office
if (( $(docker-diff $IMAGE:$ENV1 $IMAGE:$ENV2 | wc -l) > 2 )); then
    echo DIFF DETECTED PUSHING
    docker tag $IMAGE:$ENV1 $IMAGE:$ENV2
    docker push $IMAGE:$ENV2
    echo PUSHED
fi
echo CLEANING
docker rmi -f $IMAGE:$ENV1
docker rmi -f $IMAGE:$ENV2
echo CLEAN
